ALTER TABLE unit_event
    ALTER COLUMN posx TYPE smallint,
    ALTER COLUMN posy TYPE smallint,
    ALTER COLUMN unit_id TYPE smallint,
    ALTER COLUMN event TYPE smallint using
        CASE event
            WHEN 'UNIT_CREATE' THEN 1
            WHEN 'UNIT_COMPLETE' THEN 2
            WHEN 'UNIT_DESTROY' THEN 6
            WHEN 'UNIT_MORPH' THEN 7
        END,
    DROP COLUMN owned_by_bot,
    ALTER COLUMN unit_type TYPE smallint using
        CASE unit_type
            WHEN	'Terran_Marine'	THEN	0
            WHEN	'Terran_Ghost'	THEN	1
            WHEN	'Terran_Vulture'	THEN	2
            WHEN	'Terran_Goliath'	THEN	3
            WHEN	'Terran_Goliath_Turret'	THEN	4
            WHEN	'Terran_Siege_Tank_Tank_Mode'	THEN	5
            WHEN	'Terran_Siege_Tank_Tank_Mode_Turret'	THEN	6
            WHEN	'Terran_SCV'	THEN	7
            WHEN	'Terran_Wraith'	THEN	8
            WHEN	'Terran_Science_Vessel'	THEN	9
            WHEN	'Hero_Gui_Montag'	THEN	10
            WHEN	'Terran_Dropship'	THEN	11
            WHEN	'Terran_Battlecruiser'	THEN	12
            WHEN	'Terran_Vulture_Spider_Mine'	THEN	13
            WHEN	'Terran_Nuclear_Missile'	THEN	14
            WHEN	'Terran_Civilian'	THEN	15
            WHEN	'Hero_Sarah_Kerrigan'	THEN	16
            WHEN	'Hero_Alan_Schezar'	THEN	17
            WHEN	'Hero_Alan_Schezar_Turret'	THEN	18
            WHEN	'Hero_Jim_Raynor_Vulture'	THEN	19
            WHEN	'Hero_Jim_Raynor_Marine'	THEN	20
            WHEN	'Hero_Tom_Kazansky'	THEN	21
            WHEN	'Hero_Magellan'	THEN	22
            WHEN	'Hero_Edmund_Duke_Tank_Mode'	THEN	23
            WHEN	'Hero_Edmund_Duke_Tank_Mode_Turret'	THEN	24
            WHEN	'Hero_Edmund_Duke_Siege_Mode'	THEN	25
            WHEN	'Hero_Edmund_Duke_Siege_Mode_Turret'	THEN	26
            WHEN	'Hero_Arcturus_Mengsk'	THEN	27
            WHEN	'Hero_Hyperion'	THEN	28
            WHEN	'Hero_Norad_II'	THEN	29
            WHEN	'Terran_Siege_Tank_Siege_Mode'	THEN	30
            WHEN	'Terran_Siege_Tank_Siege_Mode_Turret'	THEN	31
            WHEN	'Terran_Firebat'	THEN	32
            WHEN	'Spell_Scanner_Sweep'	THEN	33
            WHEN	'Terran_Medic'	THEN	34
            WHEN	'Zerg_Larva'	THEN	35
            WHEN	'Zerg_Egg'	THEN	36
            WHEN	'Zerg_Zergling'	THEN	37
            WHEN	'Zerg_Hydralisk'	THEN	38
            WHEN	'Zerg_Ultralisk'	THEN	39
            WHEN	'Zerg_Broodling'	THEN	40
            WHEN	'Zerg_Drone'	THEN	41
            WHEN	'Zerg_Overlord'	THEN	42
            WHEN	'Zerg_Mutalisk'	THEN	43
            WHEN	'Zerg_Guardian'	THEN	44
            WHEN	'Zerg_Queen'	THEN	45
            WHEN	'Zerg_Defiler'	THEN	46
            WHEN	'Zerg_Scourge'	THEN	47
            WHEN	'Hero_Torrasque'	THEN	48
            WHEN	'Hero_Matriarch'	THEN	49
            WHEN	'Zerg_Infested_Terran'	THEN	50
            WHEN	'Hero_Infested_Kerrigan'	THEN	51
            WHEN	'Hero_Unclean_One'	THEN	52
            WHEN	'Hero_Hunter_Killer'	THEN	53
            WHEN	'Hero_Devouring_One'	THEN	54
            WHEN	'Hero_Kukulza_Mutalisk'	THEN	55
            WHEN	'Hero_Kukulza_Guardian'	THEN	56
            WHEN	'Hero_Yggdrasill'	THEN	57
            WHEN	'Terran_Valkyrie'	THEN	58
            WHEN	'Zerg_Cocoon'	THEN	59
            WHEN	'Protoss_Corsair'	THEN	60
            WHEN	'Protoss_Dark_Templar'	THEN	61
            WHEN	'Zerg_Devourer'	THEN	62
            WHEN	'Protoss_Dark_Archon'	THEN	63
            WHEN	'Protoss_Probe'	THEN	64
            WHEN	'Protoss_Zealot'	THEN	65
            WHEN	'Protoss_Dragoon'	THEN	66
            WHEN	'Protoss_High_Templar'	THEN	67
            WHEN	'Protoss_Archon'	THEN	68
            WHEN	'Protoss_Shuttle'	THEN	69
            WHEN	'Protoss_Scout'	THEN	70
            WHEN	'Protoss_Arbiter'	THEN	71
            WHEN	'Protoss_Carrier'	THEN	72
            WHEN	'Protoss_Interceptor'	THEN	73
            WHEN	'Hero_Dark_Templar'	THEN	74
            WHEN	'Hero_Zeratul'	THEN	75
            WHEN	'Hero_Tassadar_Zeratul_Archon'	THEN	76
            WHEN	'Hero_Fenix_Zealot'	THEN	77
            WHEN	'Hero_Fenix_Dragoon'	THEN	78
            WHEN	'Hero_Tassadar'	THEN	79
            WHEN	'Hero_Mojo'	THEN	80
            WHEN	'Hero_Warbringer'	THEN	81
            WHEN	'Hero_Gantrithor'	THEN	82
            WHEN	'Protoss_Reaver'	THEN	83
            WHEN	'Protoss_Observer'	THEN	84
            WHEN	'Protoss_Scarab'	THEN	85
            WHEN	'Hero_Danimoth'	THEN	86
            WHEN	'Hero_Aldaris'	THEN	87
            WHEN	'Hero_Artanis'	THEN	88
            WHEN	'Critter_Rhynadon'	THEN	89
            WHEN	'Critter_Bengalaas'	THEN	90
            WHEN	'Special_Cargo_Ship'	THEN	91
            WHEN	'Special_Mercenary_Gunship'	THEN	92
            WHEN	'Critter_Scantid'	THEN	93
            WHEN	'Critter_Kakaru'	THEN	94
            WHEN	'Critter_Ragnasaur'	THEN	95
            WHEN	'Critter_Ursadon'	THEN	96
            WHEN	'Zerg_Lurker_Egg'	THEN	97
            WHEN	'Hero_Raszagal'	THEN	98
            WHEN	'Hero_Samir_Duran'	THEN	99
            WHEN	'Hero_Alexei_Stukov'	THEN	100
            WHEN	'Special_Map_Revealer'	THEN	101
            WHEN	'Hero_Gerard_DuGalle'	THEN	102
            WHEN	'Zerg_Lurker'	THEN	103
            WHEN	'Hero_Infested_Duran'	THEN	104
            WHEN	'Spell_Disruption_Web'	THEN	105
            WHEN	'Terran_Command_Center'	THEN	106
            WHEN	'Terran_Comsat_Station'	THEN	107
            WHEN	'Terran_Nuclear_Silo'	THEN	108
            WHEN	'Terran_Supply_Depot'	THEN	109
            WHEN	'Terran_Refinery'	THEN	110
            WHEN	'Terran_Barracks'	THEN	111
            WHEN	'Terran_Academy'	THEN	112
            WHEN	'Terran_Factory'	THEN	113
            WHEN	'Terran_Starport'	THEN	114
            WHEN	'Terran_Control_Tower'	THEN	115
            WHEN	'Terran_Science_Facility'	THEN	116
            WHEN	'Terran_Covert_Ops'	THEN	117
            WHEN	'Terran_Physics_Lab'	THEN	118
            WHEN	'Unused_Terran1'	THEN	119
            WHEN	'Terran_Machine_Shop'	THEN	120
            WHEN	'Unused_Terran2'	THEN	121
            WHEN	'Terran_Engineering_Bay'	THEN	122
            WHEN	'Terran_Armory'	THEN	123
            WHEN	'Terran_Missile_Turret'	THEN	124
            WHEN	'Terran_Bunker'	THEN	125
            WHEN	'Special_Crashed_Norad_II'	THEN	126
            WHEN	'Special_Ion_Cannon'	THEN	127
            WHEN	'Powerup_Uraj_Crystal'	THEN	128
            WHEN	'Powerup_Khalis_Crystal'	THEN	129
            WHEN	'Zerg_Infested_Command_Center'	THEN	130
            WHEN	'Zerg_Hatchery'	THEN	131
            WHEN	'Zerg_Lair'	THEN	132
            WHEN	'Zerg_Hive'	THEN	133
            WHEN	'Zerg_Nydus_Canal'	THEN	134
            WHEN	'Zerg_Hydralisk_Den'	THEN	135
            WHEN	'Zerg_Defiler_Mound'	THEN	136
            WHEN	'Zerg_Greater_Spire'	THEN	137
            WHEN	'Zerg_Queens_Nest'	THEN	138
            WHEN	'Zerg_Evolution_Chamber'	THEN	139
            WHEN	'Zerg_Ultralisk_Cavern'	THEN	140
            WHEN	'Zerg_Spire'	THEN	141
            WHEN	'Zerg_Spawning_Pool'	THEN	142
            WHEN	'Zerg_Creep_Colony'	THEN	143
            WHEN	'Zerg_Spore_Colony'	THEN	144
            WHEN	'Unused_Zerg1'	THEN	145
            WHEN	'Zerg_Sunken_Colony'	THEN	146
            WHEN	'Special_Overmind_With_Shell'	THEN	147
            WHEN	'Special_Overmind'	THEN	148
            WHEN	'Zerg_Extractor'	THEN	149
            WHEN	'Special_Mature_Chrysalis'	THEN	150
            WHEN	'Special_Cerebrate'	THEN	151
            WHEN	'Special_Cerebrate_Daggoth'	THEN	152
            WHEN	'Unused_Zerg2'	THEN	153
            WHEN	'Protoss_Nexus'	THEN	154
            WHEN	'Protoss_Robotics_Facility'	THEN	155
            WHEN	'Protoss_Pylon'	THEN	156
            WHEN	'Protoss_Assimilator'	THEN	157
            WHEN	'Unused_Protoss1'	THEN	158
            WHEN	'Protoss_Observatory'	THEN	159
            WHEN	'Protoss_Gateway'	THEN	160
            WHEN	'Unused_Protoss2'	THEN	161
            WHEN	'Protoss_Photon_Cannon'	THEN	162
            WHEN	'Protoss_Citadel_of_Adun'	THEN	163
            WHEN	'Protoss_Cybernetics_Core'	THEN	164
            WHEN	'Protoss_Templar_Archives'	THEN	165
            WHEN	'Protoss_Forge'	THEN	166
            WHEN	'Protoss_Stargate'	THEN	167
            WHEN	'Special_Stasis_Cell_Prison'	THEN	168
            WHEN	'Protoss_Fleet_Beacon'	THEN	169
            WHEN	'Protoss_Arbiter_Tribunal'	THEN	170
            WHEN	'Protoss_Robotics_Support_Bay'	THEN	171
            WHEN	'Protoss_Shield_Battery'	THEN	172
            WHEN	'Special_Khaydarin_Crystal_Form'	THEN	173
            WHEN	'Special_Protoss_Temple'	THEN	174
            WHEN	'Special_XelNaga_Temple'	THEN	175
            WHEN	'Resource_Mineral_Field'	THEN	176
            WHEN	'Resource_Mineral_Field_Type_2'	THEN	177
            WHEN	'Resource_Mineral_Field_Type_3'	THEN	178
            WHEN	'Unused_Cave'	THEN	179
            WHEN	'Unused_Cave_In'	THEN	180
            WHEN	'Unused_Cantina'	THEN	181
            WHEN	'Unused_Mining_Platform'	THEN	182
            WHEN	'Unused_Independant_Command_Center'	THEN	183
            WHEN	'Special_Independant_Starport'	THEN	184
            WHEN	'Unused_Independant_Jump_Gate'	THEN	185
            WHEN	'Unused_Ruins'	THEN	186
            WHEN	'Unused_Khaydarin_Crystal_Formation'	THEN	187
            WHEN	'Resource_Vespene_Geyser'	THEN	188
            WHEN	'Special_Warp_Gate'	THEN	189
            WHEN	'Special_Psi_Disrupter'	THEN	190
            WHEN	'Unused_Zerg_Marker'	THEN	191
            WHEN	'Unused_Terran_Marker'	THEN	192
            WHEN	'Unused_Protoss_Marker'	THEN	193
            WHEN	'Special_Zerg_Beacon'	THEN	194
            WHEN	'Special_Terran_Beacon'	THEN	195
            WHEN	'Special_Protoss_Beacon'	THEN	196
            WHEN	'Special_Zerg_Flag_Beacon'	THEN	197
            WHEN	'Special_Terran_Flag_Beacon'	THEN	198
            WHEN	'Special_Protoss_Flag_Beacon'	THEN	199
            WHEN	'Special_Power_Generator'	THEN	200
            WHEN	'Special_Overmind_Cocoon'	THEN	201
            WHEN	'Spell_Dark_Swarm'	THEN	202
            WHEN	'Special_Floor_Missile_Trap'	THEN	203
            WHEN	'Special_Floor_Hatch'	THEN	204
            WHEN	'Special_Upper_Level_Door'	THEN	205
            WHEN	'Special_Right_Upper_Level_Door'	THEN	206
            WHEN	'Special_Pit_Door'	THEN	207
            WHEN	'Special_Right_Pit_Door'	THEN	208
            WHEN	'Special_Floor_Gun_Trap'	THEN	209
            WHEN	'Special_Wall_Missile_Trap'	THEN	210
            WHEN	'Special_Wall_Flame_Trap'	THEN	211
            WHEN	'Special_Right_Wall_Missile_Trap'	THEN	212
            WHEN	'Special_Right_Wall_Flame_Trap'	THEN	213
            WHEN	'Special_Start_Location'	THEN	214
            WHEN	'Powerup_Flag'	THEN	215
            WHEN	'Powerup_Young_Chrysalis'	THEN	216
            WHEN	'Powerup_Psi_Emitter'	THEN	217
            WHEN	'Powerup_Data_Disk'	THEN	218
            WHEN	'Powerup_Khaydarin_Crystal'	THEN	219
            WHEN	'Powerup_Mineral_Cluster_Type_1'	THEN	220
            WHEN	'Powerup_Mineral_Cluster_Type_2'	THEN	221
            WHEN	'Powerup_Protoss_Gas_Orb_Type_1'	THEN	222
            WHEN	'Powerup_Protoss_Gas_Orb_Type_2'	THEN	223
            WHEN	'Powerup_Zerg_Gas_Sac_Type_1'	THEN	224
            WHEN	'Powerup_Zerg_Gas_Sac_Type_2'	THEN	225
            WHEN	'Powerup_Terran_Gas_Tank_Type_1'	THEN	226
            WHEN	'Powerup_Terran_Gas_Tank_Type_2'	THEN	227
            WHEN	'None'	THEN	228
            WHEN	'AllUnits'	THEN	229
            WHEN	'Men'	THEN	230
            WHEN	'Buildings'	THEN	231
            WHEN	'Factories'	THEN	232
            WHEN	'Unknown'	THEN	233
        END;

